In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# torch.tensor creates a pytorch tensor
scalar.ndim # there's no dimensions

0

In [4]:
# get tensor back as python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([6,7])
vector

tensor([6, 7])

In [6]:
vector.ndim # vector has one dimension. Can think of this as the number of []

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape # we have 1 3x3 shaped tensor

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

![image.png](attachment:e877356f-7e87-4382-b10d-b115ebc4fb9c.png)

In [17]:
# typically for a matrix or tensor ML and Deep Learning code generally uses all caps for variable names

### Random Tensors

Why random tensors?

Random tensors are important because the way many NNs learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

Start with random nums --> look at data --> update random nums --> look at data --> update random numbers

In [18]:
# create a random tensor of size (3, 4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1822, 0.4104, 0.1073, 0.6607],
        [0.8128, 0.2677, 0.7807, 0.3131],
        [0.1089, 0.9771, 0.3812, 0.7140]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor2 = torch.rand(1, 10, 10)
random_tensor2

tensor([[[0.5942, 0.7994, 0.0044, 0.4983, 0.5382, 0.7558, 0.1460, 0.1450,
          0.1178, 0.4811],
         [0.5931, 0.4905, 0.3152, 0.7675, 0.2120, 0.8830, 0.5677, 0.9365,
          0.2187, 0.7509],
         [0.2640, 0.2253, 0.3915, 0.7876, 0.5972, 0.5341, 0.9519, 0.3759,
          0.2383, 0.1528],
         [0.1526, 0.0724, 0.8118, 0.3326, 0.7358, 0.7599, 0.3849, 0.7955,
          0.2969, 0.8044],
         [0.7201, 0.3579, 0.8433, 0.4055, 0.2388, 0.8512, 0.1899, 0.0316,
          0.7093, 0.2607],
         [0.4074, 0.8505, 0.1832, 0.5898, 0.8960, 0.0319, 0.2881, 0.0730,
          0.7319, 0.3666],
         [0.3373, 0.3467, 0.9075, 0.3476, 0.4850, 0.8297, 0.5194, 0.6145,
          0.1185, 0.0989],
         [0.2381, 0.6230, 0.2186, 0.3718, 0.7978, 0.2563, 0.7229, 0.0652,
          0.5328, 0.0516],
         [0.3742, 0.9059, 0.0881, 0.6458, 0.6964, 0.1367, 0.8172, 0.6820,
          0.9848, 0.7827],
         [0.3678, 0.3108, 0.8649, 0.1396, 0.3464, 0.4099, 0.6041, 0.9923,
          0.8344,

In [21]:
random_tensor3 = torch.rand(10, 10, 10)
random_tensor3

tensor([[[4.5739e-01, 9.8963e-01, 3.2490e-01, 3.4078e-02, 4.9313e-01,
          8.5670e-01, 9.9244e-01, 4.1354e-01, 2.1186e-01, 4.4943e-01],
         [1.0748e-02, 7.3930e-01, 2.1585e-01, 6.6016e-01, 5.2208e-01,
          1.4206e-01, 9.9892e-01, 9.4675e-01, 8.5037e-01, 4.5581e-02],
         [1.4475e-01, 6.0499e-01, 8.0082e-01, 9.3771e-01, 7.0306e-01,
          4.2951e-01, 2.0311e-01, 3.9005e-01, 7.8799e-01, 2.3471e-01],
         [9.2067e-02, 7.5675e-01, 3.6329e-01, 1.3900e-01, 3.3950e-01,
          1.3384e-01, 8.3775e-01, 3.0157e-01, 7.4369e-01, 5.2593e-01],
         [8.8699e-01, 7.1189e-01, 8.4840e-01, 2.5242e-01, 3.6569e-01,
          4.2524e-01, 5.7370e-01, 4.2676e-01, 3.5142e-01, 5.9210e-01],
         [1.2452e-01, 9.4932e-01, 9.4743e-01, 1.6850e-01, 3.6527e-01,
          8.6276e-01, 4.3456e-01, 6.9468e-01, 6.0284e-01, 2.8609e-01],
         [8.5481e-01, 3.8344e-01, 8.9067e-01, 9.4298e-01, 7.1544e-02,
          9.8956e-01, 6.0459e-02, 5.2996e-01, 1.8682e-01, 1.9502e-01],
         [3.8

In [22]:
# create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

![image.png](attachment:c10f2414-dc59-479e-bb4f-620cf7e61c6f.png)

### Zeroes and Ones

In [23]:
# tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [27]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [28]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
torch.arange(start= 0, end=1000, step=90)

tensor([  0,  90, 180, 270, 360, 450, 540, 630, 720, 810, 900, 990])

In [31]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Tensor Datatypes**

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # what datatype is the tensor. You can get more precise (64 bit) but slower execution or faster execution with lower precision (16 bit)
                              device=None, # what device is tensor on cpu (default), cuda, tpu. If you do operations on tensors with different devices you'll get an error
                              requires_grad=False) # if you want pytorch to track gradients you can set this
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor
# even though these are two different datatypes they do execute

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [38]:
long_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
long_32_tensor

tensor([3, 6, 9])

In [39]:
float_32_tensor * long_32_tensor

tensor([ 9., 36., 81.])

In [40]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1263, 0.6599, 0.0696, 0.6540],
        [0.9490, 0.8522, 0.2521, 0.7461],
        [0.3928, 0.9665, 0.3299, 0.3037]])

Tensors not the right datatype --> to do get datatype from a tensor, can use tensor.dtype

Tensors not right shape --> to get shape from tensor, can use tensor.shape

Tensors not on the right device --> to get device from a tensor, can use tensor.device

In [41]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1263, 0.6599, 0.0696, 0.6540],
        [0.9490, 0.8522, 0.2521, 0.7461],
        [0.3928, 0.9665, 0.3299, 0.3037]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include: addition, subtraction, multiplication (element-wise), division, matrix multiplication

In [42]:
# addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [43]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [44]:
# subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [45]:
# can also do in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [46]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural network and deep learning
- element-wise multiplication
- matrix multiplication (dot product)

For matrix multiplication, the inner dimensions must match. Also, the resulting matrix has the shape of the outer dimensions (basic Lin Alg)

In [47]:
print(tensor, "*", tensor)
print(tensor * tensor) # element-wise multiplication

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [48]:
# Matrix Multiplication
torch.matmul(tensor, tensor) # 1 * 1 + 2 * 2 + 3 * 3

tensor(14)

In [49]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 929 µs, sys: 110 µs, total: 1.04 ms
Wall time: 9.2 ms


In [50]:
%%time
torch.matmul(tensor, tensor) # much faster than writing a for loop

CPU times: user 353 µs, sys: 30 µs, total: 383 µs
Wall time: 1.03 ms


tensor(14)

### One of the most common errors in Deep Learning is Shape Errors

In [51]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.6085, 0.3307, 0.5862],
        [0.5782, 0.5054, 0.5694],
        [0.5035, 0.2782, 0.4853]])

In [52]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.7542, 1.0567],
        [0.9622, 1.3265]])

In [53]:
tensor_a = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_b = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
torch.mm(tensor_a, tensor_b) # torch.mm is same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix the tensor shape issues we can manipulate the shape of one of our tensors using the transpose. Transpose switches axes or dimensions of a given tensor


In [54]:
tensor_b

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [55]:
tensor_b.T, tensor_b.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [56]:
torch.matmul(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [57]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [59]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [60]:
torch.mean(x) # does not work on dtype Long

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [61]:
# find the mean - requiers tensor of float32 to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [62]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the Positional Min and Max

In [63]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
x.argmin() # find the position in tensor that has the minimum value with argmin()

tensor(0)

In [66]:
x[0]

tensor(0)

In [67]:
x.argmax() # find the position in tensor that has the maximum value with argmax()

tensor(9)

In [68]:
x[9]

tensor(90)

### Reshaping, Stacking, Squeezing, and Unsqueezing

* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze - Add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [69]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
# add an extra dimension
x_reshaped = x.reshape(1, 7) # trying to squeeze tensor of 9 elements into 7

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [104]:
x_reshaped = x.reshape(1, 9)

In [105]:
x_reshaped = x.reshape(2, 9) # cannot double the amount of elements

RuntimeError: shape '[2, 9]' is invalid for input of size 9

In [141]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape # reshape must be compatible with the original size

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [142]:
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [143]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [144]:
# changing z changes x because a view of a tensor shares the same memory as the original tensor
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [145]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[[[5, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]],
 
 
         [[[5, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]],
 
 
         [[[5, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]],
 
 
         [[[5, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]]),
 torch.Size([4, 1, 3, 3]))

In [107]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],
 
          [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],
 
          [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],
 
          [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]]),
 torch.Size([1, 4, 3, 3]))

In [108]:
x_v_stacked = torch.vstack([x,x,x,x])
x_v_stacked, x_v_stacked.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([4, 3, 3]))

In [109]:
x_h_stacked = torch.hstack([x,x,x,x])
x_h_stacked, x_h_stacked.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 12, 3]))

In [110]:
y = torch.randn(2,3)
y, y.shape

(tensor([[ 2.2082, -0.6380,  0.4617],
         [ 0.2674,  0.5349,  0.8094]]),
 torch.Size([2, 3]))

In [111]:
y_unsqueezed0 = torch.unsqueeze(y, dim=0)
y_unsqueezed0, y_unsqueezed0.shape # adds dimsion of size 1 at position 0

(tensor([[[ 2.2082, -0.6380,  0.4617],
          [ 0.2674,  0.5349,  0.8094]]]),
 torch.Size([1, 2, 3]))

In [112]:
y_unsqueezed1 = torch.unsqueeze(y, dim=2)
y_unsqueezed1, y_unsqueezed1.shape # adds dimsion of size 1 at position 2

(tensor([[[ 2.2082],
          [-0.6380],
          [ 0.4617]],
 
         [[ 0.2674],
          [ 0.5349],
          [ 0.8094]]]),
 torch.Size([2, 3, 1]))

In [113]:
y_unsqueezed1 = torch.unsqueeze(y, dim=1)
y_unsqueezed1, y_unsqueezed1.shape # adds dimsion of size 1 at position 1

(tensor([[[ 2.2082, -0.6380,  0.4617]],
 
         [[ 0.2674,  0.5349,  0.8094]]]),
 torch.Size([2, 1, 3]))

In [114]:
x = torch.randn(1,2,1,4,1)
x, x.shape

(tensor([[[[[ 1.1103],
            [-1.6898],
            [-0.9890],
            [ 0.9580]]],
 
 
          [[[ 1.3221],
            [ 0.8172],
            [-0.7658],
            [-0.7506]]]]]),
 torch.Size([1, 2, 1, 4, 1]))

In [115]:
y = torch.squeeze(x)
y, y.shape # removes all dimensions of size 1

(tensor([[ 1.1103, -1.6898, -0.9890,  0.9580],
         [ 1.3221,  0.8172, -0.7658, -0.7506]]),
 torch.Size([2, 4]))

In [116]:
z = torch.squeeze(x, dim=0)
z, z.shape # removes dimension at index if size is 1

(tensor([[[[ 1.1103],
           [-1.6898],
           [-0.9890],
           [ 0.9580]]],
 
 
         [[[ 1.3221],
           [ 0.8172],
           [-0.7658],
           [-0.7506]]]]),
 torch.Size([2, 1, 4, 1]))

In [117]:
w = torch.squeeze(x, dim=1)
w, w.shape # removes dimension at index if size is 1. Sinze it's not 1 it's not removed

(tensor([[[[[ 1.1103],
            [-1.6898],
            [-0.9890],
            [ 0.9580]]],
 
 
          [[[ 1.3221],
            [ 0.8172],
            [-0.7658],
            [-0.7506]]]]]),
 torch.Size([1, 2, 1, 4, 1]))

In [118]:
# torch.permute - rearranges the dimensions of the target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 to 1, 1 to 2, 2 to 0
print(f"Previous shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [119]:
x_original[0, 0, 0] = 10000000

In [120]:
x_original[0,0,0], x_permuted[0,0,0]

(tensor(10000000.), tensor(10000000.))

### Indexing (Selecting Data from Tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [121]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [122]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [123]:
x[0, 0], x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [124]:
x[0, 0, 0], x[0][0][0]

(tensor(1), tensor(1))

In [125]:
x[0,1,1]

tensor(5)

In [126]:
x[0, 2, 2]

tensor(9)

In [127]:
# You can also use ":" to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [128]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [129]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [130]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

### PyTorch Tensors and Numpy

PyTorch can interact with Numpy

* Data in NumPy, want in PyTorch tensor --> torch.from_nump(ndarray)
* PyTorch tensor --> NumPy --> torch.Tensor.numpy()

In [131]:
import numpy as np
import torch

array = np.arange(1., 8.)
tensor = torch.from_numpy(array) # when converting from numpy to pytorch pytorch reflects numpy's default dtatype of float64 unless otherwise specified
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [132]:
array.dtype

dtype('float64')

In [133]:
torch.arange(1.,8.0).dtype

torch.float32

In [134]:
# Change the value of the array, what will this do to the tensor?
array = array + 1
array, tensor # tensor value is not changed

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [135]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor # defaults to float32

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [136]:
tensor = tensor + 1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

### Reproducibility (Taking the Random out of Random)

`The NN learns: start with random numbers --> tensor operations --> update random numbers to try and make them better representations of the data --> loop`

To reduce the randomness in NNs and PyTorch is the concept of **random seed**

This flavors the randomness

In [137]:
# create two random tensors
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.8988, 0.1105, 0.4563, 0.9719],
        [0.3968, 0.1496, 0.4743, 0.9973],
        [0.4436, 0.9726, 0.5194, 0.5337]])
tensor([[0.7050, 0.3362, 0.7891, 0.1694],
        [0.1800, 0.7177, 0.6988, 0.5510],
        [0.2485, 0.8518, 0.0963, 0.1338]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [138]:
# random but reproducible tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_c = torch.rand(3,4)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [139]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # need to call each time to set the flavor
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Runnign Tensors and PyTorch Objects on the GPUs

GPUs is faster computation on numbers thanks to CUDA + NVIDIA + PyTorch

### Getting a GPU

1. Easiest is to use Google Collab for free GPU
2. Use your own GPU - takes some setup and investment
3. Use Cloud computing (GPC, AWS, Azure) to rent computers on the cloud and access them

Refer to PyTorch setup documentation

In [4]:
import torch
# checks for GPU access with PyTorch
torch.cuda.is_available()

True

In [3]:
!nvidia-smi

Wed Feb 18 23:12:58 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8             12W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [6]:
# device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'